# Generated by Django 3.2.8 on 2021-10-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(default=1.0)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=300)),
                ('balance', models.FloatField()),
                ('computer_name', models.CharField(default='', max_length=300)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.players')),
            ],
        ),
        migrations.CreateModel(
            name='CrashPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.FloatField(default=0.0)),
                ('cashout', models.FloatField(default=0.0)),
                ('player_name', models.CharField(default='', max_length=300)),
                ('computer_name', models.CharField(default='', max_length=300)),
                ('crash_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crash')),
            ],
        ),
    ]
